# Generated by Django 3.0.5 on 2020-09-01 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameCountry', models.CharField(blank=True, max_length=100, unique=True)),
                ('CodeCountry', models.CharField(blank=True, max_length=100, unique=True)),
                ('PopulationCountry', models.BigIntegerField(blank=True)),
                ('UserIDCountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SymCurrency', models.CharField(blank=True, max_length=30, unique=True)),
                ('NameCurrency', models.CharField(blank=True, max_length=100, unique=True)),
                ('ValueCurrency', models.IntegerField()),
                ('ValueVND', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameDegree', models.CharField(blank=True, max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameDistrict', models.CharField(blank=True, max_length=128, unique=True)),
                ('PopulationDistrict', models.IntegerField()),
                ('CodeDistrict', models.IntegerField()),
                ('type', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=128)),
                ('name_with_type', models.CharField(max_length=128)),
                ('path', models.CharField(max_length=128)),
                ('path_with_type', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'District',
                'ordering': ('NameDistrict',),
            },
        ),
        migrations.CreateModel(
            name='JobClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameJobClassification', models.CharField(blank=True, max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamePosition', models.CharField(blank=True, max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level1Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameLevel1Career', models.CharField(blank=True, max_length=128)),
                ('CodeLevel1Career', models.CharField(max_length=100)),
                ('CountLevel1Career', models.BigIntegerField(blank=True)),
            ],
            options={
                'db_table': 'Level1Career',
            },
        ),
        migrations.CreateModel(
            name='Level2Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameLevel2Career', models.CharField(blank=True, max_length=128, unique=True)),
                ('CodeLevel2Career', models.CharField(max_length=100)),
                ('CountLevel2Career', models.BigIntegerField(blank=True)),
                ('Level1CareerIDLevel2Career', models.ManyToManyField(related_name='level1career', to='addressgojoco.Level1Career')),
                ('UserIDLevel2Career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Level2Career',
                'ordering': ('NameLevel2Career',),
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameWard', models.CharField(blank=True, max_length=100, unique=True)),
                ('PopulationWard', models.IntegerField()),
                ('CodeWard', models.IntegerField()),
                ('type', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=128)),
                ('DistrictIDWard', models.ManyToManyField(related_name='districtward', to='addressgojoco.District')),
                ('UserIDWard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Ward',
            },
        ),
        migrations.CreateModel(
            name='ProvinceCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameProvinceCity', models.CharField(blank=True, max_length=128, unique=True)),
                ('PopulationProvinceCity', models.IntegerField()),
                ('CodeProvinceCity', models.IntegerField(blank=True)),
                ('slug', models.CharField(blank=True, max_length=128)),
                ('type', models.CharField(blank=True, max_length=128)),
                ('name_with_type', models.CharField(blank=True, max_length=128)),
                ('CountryIDProvinceCity', models.ManyToManyField(related_name='provincecity', to='addressgojoco.Country')),
                ('UserIDProvinceCity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ProvinceCity',
            },
        ),
        migrations.CreateModel(
            name='MainCareer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameMainCareer', models.CharField(blank=True, max_length=100, unique=True)),
                ('CodeMainCareer', models.CharField(max_length=100)),
                ('CountMainCareer', models.BigIntegerField(blank=True)),
                ('UserIDMainCareer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Level3Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameLevel3Career', models.CharField(blank=True, max_length=100, unique=True)),
                ('CodeLevel3Career', models.CharField(max_length=100)),
                ('CountLevel3Career', models.BigIntegerField(blank=True)),
                ('Level2CareerIDLevel3Career', models.ManyToManyField(related_name='level2career', to='addressgojoco.Level2Career')),
                ('UserIDLevel3Career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Level3Career',
            },
        ),
        migrations.AddField(
            model_name='level1career',
            name='MainCareerIDLevel1Career',
            field=models.ManyToManyField(related_name='maincareer', to='addressgojoco.MainCareer'),
        ),
        migrations.AddField(
            model_name='level1career',
            name='UserIDLevel1Career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LanguageUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameLanguage', models.CharField(max_length=128)),
                ('UserIDLanguage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'LanguageUser',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='ProvinceCityIDDistrict',
            field=models.ManyToManyField(related_name='provincecitydistrict', to='addressgojoco.ProvinceCity'),
        ),
        migrations.AddField(
            model_name='district',
            name='UserIDDistrict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
