from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [

    path('base/', base_views, name="base"),
    path('base_admin/', baseadmin_views, name="base-admin"),
    # --------------------------------------------------------------------------------
    path('advanced-search/', advancedsearch_views, name="advanced-search"),
    path('about/', about_views, name="about"),
    path('ad-posts/', adposts_views, name="ad-posts"),
    path('ad-posts2/', adposts2_views, name="ad-posts2"),
    path('error_400/', error_400_views, name="error_400"),
    path('error_404/', error_404_views, name="error_404"),
    path('error_404-inline/', error_404inline_views, name="error_404-inline"),
    path('error_500/', error_500_views, name="error_500"),
    path('blog-details/', blogdetails_views, name="blog-details"),
    path('blog-details-center/', blogdetailscenter_views, name="blog-details-center"),
    path('blog-details-right/', blogdetailsright_views, name="blog-details-right"),
    path('blog-grid/', bloggrid_views, name="blog-details"),
    path('blog-grid-center/', bloggridcenter_views, name="blog-grid-center"),
    path('blog-grid-right/', bloggridright_views, name="blog-grid-right"),
    path('blog-list/', bloglist_views, name="blog-list"),
    path('blog-list-center/', bloglistcenter_views, name="blog-list-center"),
    path('blog-list-right/', bloglistright_views, name="blog-list-right"),
    path('candidate-listing/', candidatelisting_views, name="candidate-listing"),
    path('candidate-listing2/', candidatelisting2_views, name="candidate-listing2"),
    path('candidate-profile/', candidateprofile_views, name="candidate-profile"),
    path('categories/', categories_views, name="categories"),
    path('company-details/', companydetails_views, name="company-details"),
    path('company-list/', companylist_views, name="company-list"),
    path('company-list2/', companylist2_views, name="company-list2"),
    path('company-list-map/', companylistmap_views, name="company-list-map"),
    path('company-list-map2/', companylistmap2_views, name="company-list-map2"),
    path('company-list-map3/', companylistmap3_views, name="company-list-map3"),
    path('company-reviews/', companyreviews_views, name="company-reviews"),
    path('contact/', contact_views, name="contact"),
    path('create_resume/', createresume_views, name="create_resume"),
    path('update_resume/<int:id>/', updateresume_views, name="update_resume"),
    path('faq/', faq_views, name="faq"),
    path('footer-style1/', footerstyle1_views, name="footer-style1"),
    path('footer-style2/', footerstyle2_views, name="footer-style2"),
    path('footer-style3/', footerstyle3_views, name="footer-style3"),
    path('footer-style4/', footerstyle4_views, name="footer-style4"),
    path('forgot/', forgot_views, name="forgot"),
    path('header-style1/', headerstyle1_views, name="header-style1"),
    path('header-style2/', headerstyle2_views, name="header-style2"),
    path('header-style3/', headerstyle3_views, name="header-style3"),
    path('header-style4/', headerstyle4_views, name="header-style4"),
    path('index/', index_views, name="index"),
    path('index2/', index2_views, name="index2"),
    path('index3/', index3_views, name="index3"),
    path('index4/', index4_views, name="index4"),
    path('index5/', index5_views, name="index5"),
    path('index6/', index6_views, name="index6"),
    path('index7/', index7_views, name="index7"),
    path('inovice/', inovice_views, name="inovice"),
    path('intro-page/', intropage_views, name="intro-page"),
    path('jobs/', jobs_views, name="jobs"),
    path('jobs-list/', jobslist_views, name="jobs-list"),
    path('jobs-list-map/', jobslistmap_views, name="jobs-list-map"),
    path('jobs-list-map2/', jobslistmap2_views, name="jobs-list-map2"),
    path('jobs-list-map3/', jobslistmap3_views, name="jobs-list-map3"),
    path('jobs-list-right/', jobslistright_views, name="jobs-list-right"),
    path('jobs-right/', jobsright_views, name="jobs-right"),
    path('lockscreen/', lockscreen_views, name="lockscreen"),
    path('login/', login_views, name="login"),
    path('login-2/', login2_views, name="login-2"),
    path('manged/', manged_views, name="manged"),
    path('my-jobs/', myjobs_views, name="my-jobs"),
    path('mydash/', mydash_views, name="mydash"),
    path('myfavorite/', myfavorite_views, name="myfavorite"),
    path('myjobs/', myjobs_views, name="myjobs"),
    path('update_job/<int:id>/', updatejob_views, name="update_job"),
    path('mycv/', mycv_views, name="mycv_views"),
    path('orders/', orders_views, name="orders"),
    path('payments/', payments_views, name="payments"),
    path('popup-login/', popuplogin_views, name="popuplogin"),
    path('pricing/', pricing_views, name="pricing"),
    path('profile/', profile_views, name="profile"),
    path('register/', register_views, name="register"),
    path('settings/', settings_views, name="settings"),
    path('tips/', tips_views, name="tips"),
    path('typography/', typography_views, name="typography"),
    path('underconstrustion/', underconstrustion_views, name="underconstrustion"),
    path('userprofile/', userprofile_views, name="userprofile"),
    path('usersall/', usersall_views, name="usersall"),
    path('widgets/', widgets_views, name="widgets"),
    path('widgetscarousel/', widgetscarousel_views, name="widgets-carousel"),
    path('widgets-verticalscroll/', widgetsverticalscroll_views, name="widgets-verticalscroll"),

    path('registeruser/', registeruser, name="registeruser"),

    path('info_employee/', info_employee, name="info_employee"),
    path('index/<int:id>/', detail_resume, name="registeruser"),

    path('updatejob/<int:id>/', detail_job, name="registeruser"),
    path('jobs/<int:id>/', jobs, name="jobs"),
    path('timekeeping/', timekeeping, name="timekeeping"),
    path('getip/', getip, name="getip"),
    path('listapply/<int:id>/', listapply, name="listapply"),

    path('viewdetailjobapply/<int:id>/', viewdetailjobapply, name="viewdetailjobapply"),

    path('createcalendar2/', createcalendar2, name="createcalendar2"),
    path('createcalendar2/<int:id>/', editschedule, name="editschedule"),

    path('listschedule/', listschedule, name="listschedule"),
    path('editschedule/<int:id>/', editschedule, name="editschedule"),
    # path('useruploadphoto/', UserUploadPhotoView.as_view(), name='uploadphoto'),
    path('listinout2/<int:id>/', listinout2, name="listinout2"),
    # path('listinout2/', listinout3, name="listinout2"),

    path('calendar2/', calendar2, name="calendar2"),
]
